#!/bin/bash
# ~/scripts/open-p3-workspace.sh

# Open PNG with Windows default viewer
cmd.exe /c start "" "C:\Users\steph\OneDrive - Région Île-de-France\Charly\Classes\P3\tromb.png"

# Open two terminal tabs with neovim
wt.exe \
  new-tab wsl.exe bash -c "nvim '/mnt/c/Users/steph/OneDrive - Région Île-de-France/Charly/Classes/P3/comments_P3.md'" \; \
  new-tab wsl.exe bash -c "nvim '/mnt/c/Users/steph/OneDrive - Région Île-de-France/Charly/classes/nts/journal_P3.md'"


