#!/bin/bash
# ~/scripts/open-p3-workspace.sh

# Open PNG with Windows default viewer
cmd.exe /c start "" "C:\Users\steph\OneDrive - Région Île-de-France\Charly\Classes\S2_S9\tromb.png"

# Open two terminal tabs with neovim
wt.exe \
  new-tab wsl.exe bash -c "nvim '/mnt/c/Users/steph/OneDrive - Région Île-de-France/Charly/Classes/S2_S9/comments_S2_S9.md'" \; \
  new-tab wsl.exe bash -c "nvim '/mnt/c/Users/steph/OneDrive - Région Île-de-France/Charly/classes/nts/journal_S2_S9.md'"


i
