#!/bin/bash
# ~/scripts/open-t9-workspace.sh

# Open PNG with Windows default viewer
cmd.exe /c start "" "C:\Users\steph\OneDrive - Région Île-de-France\Charly\Classes\T9\tromb.png"

# Open two terminal tabs with neovim
wt.exe \
  new-tab wsl.exe bash -c "nvim '/mnt/c/Users/steph/OneDrive - Région Île-de-France/Charly/Classes/P9/comments_T9.md'" \; \
  new-tab wsl.exe bash -c "nvim '/mnt/c/Users/steph/OneDrive - Région Île-de-France/Charly/classes/nts/journal_T9.md'"

